### PR TITLE
Use triple double-quotes for docstrings (PEP 257)

### PR DESCRIPTION
**Pull request by delirious-lettuce**
> For consistency, always use """triple double quotes""" around docstrings.
* https://www.python.org/dev/peps/pep-0257/#what-is-a-docstring

### CODE REVIEW

**Comment by delirious-lettuce** [comment]
@matthewwardrop ,

Oh ok, I didn't know that. Just wanted to help!

**Comment by matthewwardrop** [comment]
@delirious-lettuce Don't be sorry! The patch is definitely helpful, and now we know that we won't miss these issues in the upcoming documentation dump (which you couldn't have known about!). Really appreciate your patches!

**Comment by delirious-lettuce** [comment]
@matthewwardrop ,

Ok, cool! Happy New Years too!

**Comment by matthewwardrop** [comment]
You too! And out of curiosity, how are you using `omniduct`?

**Comment by delirious-lettuce** [comment]
I came across it by accident (I think on the Discover Repositories tab) but I am experimenting with it to use for something at work (nothing official, just tinkering for now).

**Comment by matthewwardrop** [comment]
Excellent! Well... let me know if you need any help getting it deployed/whatever. Would love to see this more widely adopted!

**Comment by delirious-lettuce** [comment]
I appreciate the offer, thanks!

**Pull request merged**
