### PR TITLE
Add `exist_ok` to the signature of `FileSystemClient.mkdir`

### PR DESCRIPTION
**Pull request by harsham4026**
this shows if the users tries to create the same folder which already exists

### CODE REVIEW

**Comment by matthewwardrop** [comment]
Thanks for your patch @harsham4026 !

As noted in #71, the decision not to warn was intentional, in that this `mkdir` method is used in contexts where all you care about is whether the directory exists, rather than whether it already exists when you ran `mkdir`. I think the right way forward is to add an `exist_ok=False` argument to the method signature (mimicking `os.makedirs`), and update the code everywhere else. I'll do this now, and add you as a co-author.

**Comment by harsham4026** [comment]
@matthewwardrop sure. thanks :)

**Comment by matthewwardrop** [comment]
@harsham4026 Does this change satisfy your use-cases?

**Comment by harsham4026** [comment]
@matthewwardrop yes. It looks good :)

**Comment by matthewwardrop** [comment]
Great! Thanks again @harsham4026

**Pull request merged**
